server:
  port: 8080
  servlet:
    session:
      timeout: 300h

spring:
  dubbo:
      application:
        name: provider
      server: true
      registry:
        address: zookeeper://127.0.0.1:2181
      protocol:
        name: dubbo
        port: 20880
  datasource:
    name: university_graduation_project
    url: jdbc:mysql://localhost:3306/university_graduation_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Lkflkf456456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 20
      max-wait: 5000
      filters: stat,wall,log4j2
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 2000ms
        max-idle: 8
        min-idle: 0
    timeout: 200s
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


